### PR TITLE
Fixed bug in video_detect due to face threshold

### PR DESCRIPTION
**Pull request by ljchang**
Multiple users have reported a bug in the video detector, in which the face detector and pose detector return a different number of detected faces #155.

In debugging this, I have noticed two code additions, which seem like they might have been trying to address this issue, but instead were actually causing it. I personally think we should remove both of these as they are both fairly kludgy and not really elegantly solving any problem.
1. face detector had an arbitrary threshold of 0.5 assigned. This was too liberal and was detecting false positives and caused a conflict with the pose detection, which detected the correct number of faces. Only the image detector had a keyword argument to change the face detection threshold
2. There is a check in image detection to compare the number of faces found by face and pose detection algorithms and a flag to skip images that find a different number of faces.

In this PR, I have made several updates that I proposed in #155 discussion.
1. I have added the same check_detection to the video detection that was in the image detection.
2. I have added threshold keyword to video detection to be consistent with image detection
3. I have changed default threshold detection to 0.9 from 0.5.
4. I have added new methods to the bounding box class to compute the overlap between boxes. Ultimately, I think a better approach to reconciling inconsistencies is to match the faces and set the inconsistent face to nans.  This can easily be done by comparing percent overlap of each bounding box detected within a frame by the face or pose detection algorithm using something like this:

```
detector_cpu = Detector(verbose=False, device='cpu')
data = VideoDataset(video_path)

frame = 160

faces = detector_cpu.detect_faces(data.video[frame,:,:,:], threshold=0.5)
# faces_pose, pose = detector_cpu.detect_facepose(data.video[frame,:,:,:]) # This doesnt work yet as we only currently return poses not poses,faces
faces_pose, poses = detector_cpu.facepose_detector(convert_image_to_tensor(data.video[frame,:,:,:], img_type="float32") / 255) # Need to go directly to model instead of high level pose detector method for now.
    
# overlap array contains the percent overlap of every detected face from face detector from the pose detector
overlap = np.zeros([len(faces[0]), len(faces_pose[0])])
for i,face in enumerate(faces[0]):
    b1 = BBox(face[:-1])
    for j,face_pose in enumerate(faces_pose[0]):
        b2 = BBox(faces_pose[0][0][:-1])
        overlap[i,j] = (b1.overlap(b2))
```

Even though, solutions 1 & 2 technically fix the problem, it is a very kludgy solution that I'm not happy with, but will allow users to make progress with their data without us spending too much more time on this.

### CODE REVIEW

**Comment by TiankangXie** [comment]
* Refactor detection waterfall and add check for img2pose 
* Add check for when user combines img2pose with another model, use Luke's facial overlap code above
* In img2pose, pass faces output along with the pose outputs

**Comment by ljchang** [comment]
A bug was reported that detectors would fail if no faces are detected #158. Added code to fix this and will return nans in the fex row. 

@ejolly: we also need to add another image that contains no faces to our test suite.

Hopefully, this fix will work for all detectors, but I haven't fully tested it yet.

**Comment by ljchang** [comment]
@ejolly I added some tests for testing images with no faces. 

There are a couple of things that need to be addressed before these can be merged.  1. no_face_img with batching isn't working yet.
2. frame indices aren't working (not sure if they ever were working perfectly
3. for some reason `test_detect_video` isn't working, it's detecting the same face twice.

I'm done for tonight, not sure when I'll have time to finish. feel free to take a look if you have time soon.

**Comment by ljchang** [comment]
@ejolly & @TiankangXie . I removed the kludgy code to check for face and pose inconsistencies. Now we attempt to match faces and poses and return nans if more faces are detected then poses. I know the matching is working and added a few tests, but I haven't fully tested everything yet. This required changing the output of the pose detector to also return bounding boxes, which could inadvertently mess up some other tests.  Will spend more time finalizing this tomorrow.

I still need to figure out why the frame counter and batching isn't working for when there are no faces detected.  We should be good to go with all of the major new bugs detected after i finalize this part.

**Comment by ljchang** [comment]
- [ ] Clean up face detection thresholding
- [ ] Match detected faces to detected poses, return nans otherwise
- [ ] Handle frames with no faces
- [ ] Fix frame counter
- [ ] Fix batching when there are frames with no faces
- [ ] Add tests for matching
- [ ] Add tests for frames with no faces

**Comment by ljchang** [comment]
@ejolly & @TiankangXie : So close to having this done, but this batching issue goes very deep!  It's like an onion that I have to keep unraveling. It's partly an issue due to how we are representing data as a list of lists.  In a future refactor, we might want to consider switching away from this list of lists data representation for detectors. It's a nightmare and super hard to debug.  

Now, I'm actually having to go deeper into individual detectors as this bug is also interacting with our tensor representations. If no face is detected within a batch, we can't extract the faces and stack them as a tensor. Still trying to come up with the best strategy. 

Option 1: create a fake image when no face is detected to avoid changing the detectors

Option 2: might require looping over images within a batch to check if it is empty. Definitely not ideal

Option 3: would be to drop the image, but store the file name and index and add it to the Fex object after detection is done.

None of these options are ideal, will keep working on it, but need to stop for the evening. Everything else is done and I believe is working except for this deep bug.

**Comment by ljchang** [comment]
ok, had to change a bunch of things, but I think batching is now working when no face is present in a frame.

Running tests now to make sure everything is passing.

There are two things we should confirm before merging:
1. @TiankangXie for hog features for AU and emotion is the dimension of the hog features fixed? Meaning is it always the same for a 112 x 112 frame? If not, we need to come up with a new solution as I'm passing a vector of zeros when no face is detected to keep the shapes the same when running batches.
2. I've only been testing on images, need to confirm this works on a video that has frames without faces.  Do we have a video like this included in our test data @ejolly or @TiankangXie ?

**Comment by ljchang** [comment]
tests are passing!

**Comment by ljchang** [comment]
@ejolly: everything seems to working. Ready for code review and merge.

**Comment by ejolly** [comment]
Ohh awesome will take a look tomorrow!

**Comment by ljchang** [comment]
> 
Great thanks!  It would be great to get this turned around quickly as this addresses very annoying and common bugs for users.

I cleaned up a bunch of things and made two main updates to address the bugs being reported by users.
1. All of the detectors have been updated to accommodate missing frames. The list of list detector output makes this way more difficult then it should be. In the future we should consider refactoring this, but it will be a decent amount of work as it affects a lot of functions, but I suspect we could cut a lot of code with this as most of it is dealing with this stupid format.
2. I added a new helper function to deal with discrepancies between detected faces and poses. The function is a little clunky and it definitely adds a small amount of overhead to the overall detection, but it handles everything in a sensible way and is hopefully relatively easy to read despite not being very elegant. Here is a quick overview of the rules:
- if more faces then poses, match faces to poses using overlap in bounding boxes and insert nans for the unaccounted poses
- if more poses than faces, match faces to poses and drop additional poses

**Comment by ljchang** [comment]
@ejolly: didn't have time to go in depth, but is there any particular reason to make the helper functions class methods?  I actually intentionally moved those out so that they can be more generally used. I was actually even thinking about moving the matching function to the image_operations module.  It's annoying if you have to initialize a detector class to use the functions.

**Comment by ejolly** [comment]
@ljchang Oh I made that change after explicitly looking to see where those functions were used throughout the package and they weren't used as generally as they seemed. It was odd from a organization and maintenance standpoint to have free floating functions in the `detector.py` instead of explicitly storing just the `Detector` class code there, though I understand why you did it. Changing them to static methods gives us the following advantages for now, but we can refactor later in case we do in fact use them more generally (we're not now):

- makes more sense to keep them as part of the class since that's the interface they're most directly affecting
- `@staticmethod` doesn't incur any overhead of needing to create an *instance* of the class. So you can use it like this: `Detector._match_faces_to_poses()` OR like this `Detector()._match_faces_to_poses()` if you already have an initialized detector. 
- I left some notes about refactoring our list of lists data representation into a Python Dataclass in the future. So having these be part of the `Detector` class allows us to evolve in the API into two interfaces (`Detector` and `Detections`) "talking" to each other, rather than a bunch of random functions lying around

**Review by ejolly — APPROVED** [review]

**Comment by ejolly** [comment]
Alrighty @ljchang this looks good to go to me, as soon as tests pass. I added some additional videos and tests to make sure we can handle those cases. If I'm not missing anything I can merge this in and cut a new release from master, when the CI finishes.

**Comment by ejolly** [comment]
Alright @ljchang I implemented that refactor I was mentioning. Let me know if there was anything else you wanted to address in this PR otherwise I can merge and prep a release.

**Comment by ljchang** [comment]
Great!  Thanks @ejolly for going through all of this. it was a lot of changes. I didn't change any other functions to use those helper functions, so they are just being used in the detector class for now. Makes sense to keep them as static methods for now. We can always adjust in the future. I'm in favor of keeping things consistent across detect_image and detect_video especially as we are still getting lots of bug reports. I can try and take a look at the waterfall method you wrote if you want, but that sounds good to me if you want. Otherwise, we can save it for the next release. Feel free to merge when you're comfortable.

**Pull request merged**
