### PR TITLE
AU fixes + more efficient video processing

### PR DESCRIPTION
**Pull request by ejolly**
This PR combines #169  and #170. Here are copied details of those PRs for posterity:

#169 
- Fix issue with PIL normalization
- Retrain AU models
- Update [tutorial 8](https://py-feat.org/extra_tutorials/08_train_hogs.html) with training code using py-feat utility functions
- Upload new model weights
- Update path to model weights [SL_test module](in https://github.com/cosanlab/py-feat/blob/main/feat/au_detectors/StatLearning/SL_test.py)

#170 

This is an attempt to dramatically lower the memory usage of .detect_video() This PR touches #139 and #165.

Previously we were relying on torch's read_video which always reads all video frames into memory at once. Our skip_frames was then used to slice the frame data during processing to speed things up. This approach is reasonable for short videos, videos with lower framerates, or smaller resolutions, but incrediby inefficient for larger files.

We had hoped there would be an informative error from the torch side of things in case this process failed when running out of memory, but multiple user reports (and validated locally) show that the kernel just crashes, hangs, or even causes a computuer freeze...hardly a graceful failure.

While torch has a VideoReader class, it's currently in beta and using it requires compiling torch from source 🙃.

I first tried storing video frame-counts and making repeated calls to read_video on a per-frame basis, but getting the pts and timing right was non-trivial.

So in order to avoid adding another hard-to-install dependency like openCV, this PR now uses a trick to lazy load video-frames by wrapping and slicing a pyav generator object; the library that torch's read_video uses under-the-hood.

We also now include approximate times for each processed frame as a column the Fex output. Also I realized that parallelization is possible on top of batching because DataLoader takes a num_workers arg. For this reason I'm going to keep the current strategy with creating a new generator for each call to load_frame in VideoDataset instead of using a single shared generator to avoid race conditions.

### CODE REVIEW

**Comment by ejolly** [comment]
@ljchang This PR now incorporates the new models @TiankangXie trained and my video processing update. After you get a chance to test this locally we can merge it in and cut a release

**Comment by ljchang** [comment]
great thanks @ejolly !  I just spoke with @TiankangXie. I can take a stab at this today and over the weekend.

**Comment by TiankangXie** [comment]
Great! Thanks @ejolly @ljchang

**Comment by ljchang** [comment]
ok, @ejolly. I think this is ready to merge into the main release and we should start a tag with this release and all subsequent major updates moving forward.

based on our testing, this update to the video loading solves previous issues running detection on large videos, which previously required loading the entire video into ram. This update solves that problem by only loading small subsets of the video at a time. However, this is at the expense of computational efficiency. In my tests, this update runs substantially slower on GPUs. We now only get about a 2x speed up instead of a 4x speed up. As we discussed, this is likely due to the additional I/O overhead that grows linearly as a function of the video length. I think at this point it is better to optimize for end user experience at the expense of speed, but we can revisit this issue in the future. Thanks!

**Pull request merged**
